version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: auctionhouse
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  auction-house:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - 80:8080
    environment:
      PROFILE: dev
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/auctionhouse?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "admin"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true


volumes:
  db: